//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEquipmentRepair.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataComment
    {
        public int commentID { get; set; }
        public string message { get; set; }
        public int masterID { get; set; }
        public int requestID { get; set; }
    
        public virtual DataRequest DataRequest { get; set; }
        public virtual DataUser DataUser { get; set; }
    }
}
