//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEquipmentRepair.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DataRequest
    {
        DEMEntities name = new DEMEntities();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataRequest()
        {
            this.DataComments = new HashSet<DataComment>();
        }
    
        public int requestID { get; set; }
        public System.DateTime startDate { get; set; }
        public int id_orgTechType { get; set; }
        public string type
        {
            get
            {
                var types = name.OrgTechTypes.FirstOrDefault(c => c.id == id_orgTechType);
                return types.name;
            }
            set
            {

            }
        }
        public string orgTechModel { get; set; }
        public int id_problemDescryption { get; set; }

        public string problem
        {
            get
            {
                var problems = name.ProblemDescryptions.FirstOrDefault(c => c.id == id_problemDescryption);
                return problems.name;
            }
            set
            {

            }
        }

        public int id_requestStatus { get; set; }

        public string status
        {
            get
            {
                var statuses = name.RequestStatuses.FirstOrDefault(c => c.id == id_requestStatus);
                return statuses.name;
            }
            set
            {

            }

        }

        public Nullable<System.DateTime> completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> masterID { get; set; }
        public int clientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataComment> DataComments { get; set; }
        public virtual DataUser DataUser { get; set; }
        public virtual DataUser DataUser1 { get; set; }
        public virtual OrgTechType OrgTechType { get; set; }
        public virtual ProblemDescryption ProblemDescryption { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
    }
}
