//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string name { get; set; }
        public string oname { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<int> id_role { get; set; }
    
        public virtual role role { get; set; }
    }
}
